

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Volunteer : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Volunteer entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Volunteer()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Volunteer(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Volunteer> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Volunteer.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int VolunteerId
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.VolunteerId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VolunteerId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VolunteerId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VolunteerId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FirstName
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.FirstName);
            }
            set
            {
                global::LightSwitchApplication.Volunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.FirstName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Surname
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.Surname);
            }
            set
            {
                global::LightSwitchApplication.Volunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.Surname, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Surname_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Surname_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Surname_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.CourseVolunteer> CourseVolunteers
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.CourseVolunteers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CourseVolunteer> CourseVolunteersQuery
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetQuery(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.CourseVolunteers);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.CrbCheck> CrbChecks
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.CrbChecks);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CrbCheck> CrbChecksQuery
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetQuery(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.CrbChecks);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.PlayVolunteer> PlayVolunteers
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.PlayVolunteers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PlayVolunteer> PlayVolunteersQuery
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetQuery(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.PlayVolunteers);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ProductionVolunteer> ProductionVolunteers
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.ProductionVolunteers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ProductionVolunteer> ProductionVolunteersQuery
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetQuery(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.ProductionVolunteers);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.VolunteerCapability> VolunteerCapabilities
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.VolunteerCapabilities);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.VolunteerCapability> VolunteerCapabilitiesQuery
        {
            get
            {
                return global::LightSwitchApplication.Volunteer.DetailsClass.GetQuery(this, global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.VolunteerCapabilities);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Volunteer,
                global::LightSwitchApplication.Volunteer.DetailsClass,
                global::LightSwitchApplication.Volunteer.DetailsClass.IImplementation,
                global::LightSwitchApplication.Volunteer.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.VolunteerId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass>.Entry
                __VolunteerEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass>.Entry(
                    global::LightSwitchApplication.Volunteer.DetailsClass.__Volunteer_CreateNew,
                    global::LightSwitchApplication.Volunteer.DetailsClass.__Volunteer_Created,
                    global::LightSwitchApplication.Volunteer.DetailsClass.__Volunteer_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Volunteer __Volunteer_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Volunteer> es)
            {
                return new global::LightSwitchApplication.Volunteer(es);
            }
            private static void __Volunteer_Created(global::LightSwitchApplication.Volunteer e)
            {
                e.Volunteer_Created();
            }
            private static bool __Volunteer_AllowSaveWithErrors(global::LightSwitchApplication.Volunteer e)
            {
                bool result = false;
                e.Volunteer_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Volunteer.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, int> VolunteerId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.VolunteerId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string> FirstName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.FirstName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string> Surname
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.Surname) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CourseVolunteer> CourseVolunteers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.CourseVolunteers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CourseVolunteer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CrbCheck> CrbChecks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.CrbChecks) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CrbCheck>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.PlayVolunteer> PlayVolunteers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.PlayVolunteers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.PlayVolunteer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.ProductionVolunteer> ProductionVolunteers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.ProductionVolunteers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.VolunteerCapability> VolunteerCapabilities
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.VolunteerCapabilities) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.VolunteerCapability>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int VolunteerId { get; }
                new string FirstName { get; set; }
                new string Surname { get; set; }
                new global::System.Collections.IEnumerable CourseVolunteers { get; }
                new global::System.Collections.IEnumerable CrbChecks { get; }
                new global::System.Collections.IEnumerable PlayVolunteers { get; }
                new global::System.Collections.IEnumerable ProductionVolunteers { get; }
                new global::System.Collections.IEnumerable VolunteerCapabilities { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, int>.Entry
                    VolunteerId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, int>.Entry(
                        "VolunteerId",
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._VolunteerId_Stub,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._VolunteerId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._VolunteerId_Validate,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._VolunteerId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._VolunteerId_OnValueChanged);
                private static void _VolunteerId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Volunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, int>.Data> c, global::LightSwitchApplication.Volunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._VolunteerId, sf);
                }
                private static bool _VolunteerId_ComputeIsReadOnly(global::LightSwitchApplication.Volunteer e)
                {
                    bool result = false;
                    e.VolunteerId_IsReadOnly(ref result);
                    return result;
                }
                private static void _VolunteerId_Validate(global::LightSwitchApplication.Volunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VolunteerId_Validate(r);
                }
                private static int _VolunteerId_GetImplementationValue(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.VolunteerId;
                }
                private static void _VolunteerId_OnValueChanged(global::LightSwitchApplication.Volunteer e)
                {
                    e.VolunteerId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>.Entry
                    FirstName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>.Entry(
                        "FirstName",
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._FirstName_Stub,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._FirstName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._FirstName_Validate,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._FirstName_GetImplementationValue,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._FirstName_SetImplementationValue,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._FirstName_OnValueChanged);
                private static void _FirstName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Volunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>.Data> c, global::LightSwitchApplication.Volunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._FirstName, sf);
                }
                private static bool _FirstName_ComputeIsReadOnly(global::LightSwitchApplication.Volunteer e)
                {
                    bool result = false;
                    e.FirstName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FirstName_Validate(global::LightSwitchApplication.Volunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FirstName_Validate(r);
                }
                private static string _FirstName_GetImplementationValue(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.FirstName;
                }
                private static void _FirstName_SetImplementationValue(global::LightSwitchApplication.Volunteer.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FirstName = v;
                }
                private static void _FirstName_OnValueChanged(global::LightSwitchApplication.Volunteer e)
                {
                    e.FirstName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>.Entry
                    Surname = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>.Entry(
                        "Surname",
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._Surname_Stub,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._Surname_ComputeIsReadOnly,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._Surname_Validate,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._Surname_GetImplementationValue,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._Surname_SetImplementationValue,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._Surname_OnValueChanged);
                private static void _Surname_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Volunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>.Data> c, global::LightSwitchApplication.Volunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._Surname, sf);
                }
                private static bool _Surname_ComputeIsReadOnly(global::LightSwitchApplication.Volunteer e)
                {
                    bool result = false;
                    e.Surname_IsReadOnly(ref result);
                    return result;
                }
                private static void _Surname_Validate(global::LightSwitchApplication.Volunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Surname_Validate(r);
                }
                private static string _Surname_GetImplementationValue(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.Surname;
                }
                private static void _Surname_SetImplementationValue(global::LightSwitchApplication.Volunteer.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Surname = v;
                }
                private static void _Surname_OnValueChanged(global::LightSwitchApplication.Volunteer e)
                {
                    e.Surname_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Entry
                    CourseVolunteers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Entry(
                        "CourseVolunteers",
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._CourseVolunteers_Stub,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._CourseVolunteers_GetReferencedEntities,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._CourseVolunteers_GetEntityCollection);
                private static void _CourseVolunteers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Volunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Data> c, global::LightSwitchApplication.Volunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseVolunteers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.CourseVolunteer> _CourseVolunteers_GetReferencedEntities(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.CourseVolunteer, global::LightSwitchApplication.CourseVolunteer.DetailsClass>(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.CourseVolunteers, ref d._CourseVolunteers);
                }
                private static global::System.Collections.IEnumerable _CourseVolunteers_GetEntityCollection(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseVolunteers;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CrbCheck>.Entry
                    CrbChecks = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CrbCheck>.Entry(
                        "CrbChecks",
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._CrbChecks_Stub,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._CrbChecks_GetReferencedEntities,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._CrbChecks_GetEntityCollection);
                private static void _CrbChecks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Volunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CrbCheck>.Data> c, global::LightSwitchApplication.Volunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._CrbChecks, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.CrbCheck> _CrbChecks_GetReferencedEntities(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass>(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.CrbChecks, ref d._CrbChecks);
                }
                private static global::System.Collections.IEnumerable _CrbChecks_GetEntityCollection(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.CrbChecks;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.PlayVolunteer>.Entry
                    PlayVolunteers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.PlayVolunteer>.Entry(
                        "PlayVolunteers",
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._PlayVolunteers_Stub,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._PlayVolunteers_GetReferencedEntities,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._PlayVolunteers_GetEntityCollection);
                private static void _PlayVolunteers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Volunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.PlayVolunteer>.Data> c, global::LightSwitchApplication.Volunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._PlayVolunteers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.PlayVolunteer> _PlayVolunteers_GetReferencedEntities(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass>(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.PlayVolunteers, ref d._PlayVolunteers);
                }
                private static global::System.Collections.IEnumerable _PlayVolunteers_GetEntityCollection(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.PlayVolunteers;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Entry
                    ProductionVolunteers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Entry(
                        "ProductionVolunteers",
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._ProductionVolunteers_Stub,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._ProductionVolunteers_GetReferencedEntities,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._ProductionVolunteers_GetEntityCollection);
                private static void _ProductionVolunteers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Volunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Data> c, global::LightSwitchApplication.Volunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductionVolunteers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ProductionVolunteer> _ProductionVolunteers_GetReferencedEntities(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass>(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.ProductionVolunteers, ref d._ProductionVolunteers);
                }
                private static global::System.Collections.IEnumerable _ProductionVolunteers_GetEntityCollection(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductionVolunteers;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.VolunteerCapability>.Entry
                    VolunteerCapabilities = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.VolunteerCapability>.Entry(
                        "VolunteerCapabilities",
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._VolunteerCapabilities_Stub,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._VolunteerCapabilities_GetReferencedEntities,
                        global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties._VolunteerCapabilities_GetEntityCollection);
                private static void _VolunteerCapabilities_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Volunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.VolunteerCapability>.Data> c, global::LightSwitchApplication.Volunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._VolunteerCapabilities, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.VolunteerCapability> _VolunteerCapabilities_GetReferencedEntities(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.VolunteerCapability, global::LightSwitchApplication.VolunteerCapability.DetailsClass>(global::LightSwitchApplication.Volunteer.DetailsClass.PropertySetProperties.VolunteerCapabilities, ref d._VolunteerCapabilities);
                }
                private static global::System.Collections.IEnumerable _VolunteerCapabilities_GetEntityCollection(global::LightSwitchApplication.Volunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.VolunteerCapabilities;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, int>.Data _VolunteerId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>.Data _FirstName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, string>.Data _Surname;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Data _CourseVolunteers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.CrbCheck>.Data _CrbChecks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.PlayVolunteer>.Data _PlayVolunteers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Data _ProductionVolunteers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass, global::LightSwitchApplication.VolunteerCapability>.Data _VolunteerCapabilities;
            
        }
    
        #endregion
    }
    
    #endregion
}
