

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class PlayVolunteer : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the PlayVolunteer entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PlayVolunteer()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PlayVolunteer(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PlayVolunteer> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.PlayVolunteer.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlayVolunteer_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlayVolunteer_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PlayId
        {
            get
            {
                return global::LightSwitchApplication.PlayVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.PlayId);
            }
            set
            {
                global::LightSwitchApplication.PlayVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.PlayId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlayId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlayId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlayId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int VolunteerId
        {
            get
            {
                return global::LightSwitchApplication.PlayVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.VolunteerId);
            }
            set
            {
                global::LightSwitchApplication.PlayVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.VolunteerId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VolunteerId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VolunteerId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VolunteerId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int JobId
        {
            get
            {
                return global::LightSwitchApplication.PlayVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.JobId);
            }
            set
            {
                global::LightSwitchApplication.PlayVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.JobId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Notes
        {
            get
            {
                return global::LightSwitchApplication.PlayVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Notes);
            }
            set
            {
                global::LightSwitchApplication.PlayVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Notes, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Notes_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Notes_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Notes_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Job Job
        {
            get
            {
                return global::LightSwitchApplication.PlayVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Job);
            }
            set
            {
                global::LightSwitchApplication.PlayVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Job, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Play Play
        {
            get
            {
                return global::LightSwitchApplication.PlayVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Play);
            }
            set
            {
                global::LightSwitchApplication.PlayVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Play, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Play_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Play_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Play_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Volunteer Volunteer
        {
            get
            {
                return global::LightSwitchApplication.PlayVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Volunteer);
            }
            set
            {
                global::LightSwitchApplication.PlayVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Volunteer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.PlayVolunteer,
                global::LightSwitchApplication.PlayVolunteer.DetailsClass,
                global::LightSwitchApplication.PlayVolunteer.DetailsClass.IImplementation,
                global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.PlayId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass>.Entry
                __PlayVolunteerEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass>.Entry(
                    global::LightSwitchApplication.PlayVolunteer.DetailsClass.__PlayVolunteer_CreateNew,
                    global::LightSwitchApplication.PlayVolunteer.DetailsClass.__PlayVolunteer_Created,
                    global::LightSwitchApplication.PlayVolunteer.DetailsClass.__PlayVolunteer_AllowSaveWithErrors);
            private static global::LightSwitchApplication.PlayVolunteer __PlayVolunteer_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PlayVolunteer> es)
            {
                return new global::LightSwitchApplication.PlayVolunteer(es);
            }
            private static void __PlayVolunteer_Created(global::LightSwitchApplication.PlayVolunteer e)
            {
                e.PlayVolunteer_Created();
            }
            private static bool __PlayVolunteer_AllowSaveWithErrors(global::LightSwitchApplication.PlayVolunteer e)
            {
                bool result = false;
                e.PlayVolunteer_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int> PlayId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.PlayId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int> VolunteerId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.VolunteerId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int> JobId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.JobId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, string> Notes
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Notes) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Job> Job
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Job) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Job>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Play> Play
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Play) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Play>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer> Volunteer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Volunteer) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int PlayId { get; set; }
                new int VolunteerId { get; set; }
                new int JobId { get; set; }
                new string Notes { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Job { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Play { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Volunteer { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Entry
                    PlayId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Entry(
                        "PlayId",
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._PlayId_Stub,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._PlayId_ComputeIsReadOnly,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._PlayId_Validate,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._PlayId_GetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._PlayId_SetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._PlayId_OnValueChanged);
                private static void _PlayId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Data> c, global::LightSwitchApplication.PlayVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._PlayId, sf);
                }
                private static bool _PlayId_ComputeIsReadOnly(global::LightSwitchApplication.PlayVolunteer e)
                {
                    bool result = false;
                    e.PlayId_IsReadOnly(ref result);
                    return result;
                }
                private static void _PlayId_Validate(global::LightSwitchApplication.PlayVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PlayId_Validate(r);
                }
                private static int _PlayId_GetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.PlayId;
                }
                private static void _PlayId_SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d, int v)
                {
                    d.ImplementationEntity.PlayId = v;
                }
                private static void _PlayId_OnValueChanged(global::LightSwitchApplication.PlayVolunteer e)
                {
                    e.PlayId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Entry
                    VolunteerId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Entry(
                        "VolunteerId",
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._VolunteerId_Stub,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._VolunteerId_ComputeIsReadOnly,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._VolunteerId_Validate,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._VolunteerId_GetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._VolunteerId_SetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._VolunteerId_OnValueChanged);
                private static void _VolunteerId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Data> c, global::LightSwitchApplication.PlayVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._VolunteerId, sf);
                }
                private static bool _VolunteerId_ComputeIsReadOnly(global::LightSwitchApplication.PlayVolunteer e)
                {
                    bool result = false;
                    e.VolunteerId_IsReadOnly(ref result);
                    return result;
                }
                private static void _VolunteerId_Validate(global::LightSwitchApplication.PlayVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VolunteerId_Validate(r);
                }
                private static int _VolunteerId_GetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.VolunteerId;
                }
                private static void _VolunteerId_SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d, int v)
                {
                    d.ImplementationEntity.VolunteerId = v;
                }
                private static void _VolunteerId_OnValueChanged(global::LightSwitchApplication.PlayVolunteer e)
                {
                    e.VolunteerId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Entry
                    JobId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Entry(
                        "JobId",
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._JobId_Stub,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._JobId_ComputeIsReadOnly,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._JobId_Validate,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._JobId_GetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._JobId_SetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._JobId_OnValueChanged);
                private static void _JobId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Data> c, global::LightSwitchApplication.PlayVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._JobId, sf);
                }
                private static bool _JobId_ComputeIsReadOnly(global::LightSwitchApplication.PlayVolunteer e)
                {
                    bool result = false;
                    e.JobId_IsReadOnly(ref result);
                    return result;
                }
                private static void _JobId_Validate(global::LightSwitchApplication.PlayVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.JobId_Validate(r);
                }
                private static int _JobId_GetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.JobId;
                }
                private static void _JobId_SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d, int v)
                {
                    d.ImplementationEntity.JobId = v;
                }
                private static void _JobId_OnValueChanged(global::LightSwitchApplication.PlayVolunteer e)
                {
                    e.JobId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, string>.Entry
                    Notes = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, string>.Entry(
                        "Notes",
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Notes_Stub,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Notes_ComputeIsReadOnly,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Notes_Validate,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Notes_GetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Notes_SetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Notes_OnValueChanged);
                private static void _Notes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, string>.Data> c, global::LightSwitchApplication.PlayVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._Notes, sf);
                }
                private static bool _Notes_ComputeIsReadOnly(global::LightSwitchApplication.PlayVolunteer e)
                {
                    bool result = false;
                    e.Notes_IsReadOnly(ref result);
                    return result;
                }
                private static void _Notes_Validate(global::LightSwitchApplication.PlayVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Notes_Validate(r);
                }
                private static string _Notes_GetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.Notes;
                }
                private static void _Notes_SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Notes = v;
                }
                private static void _Notes_OnValueChanged(global::LightSwitchApplication.PlayVolunteer e)
                {
                    e.Notes_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Job>.Entry
                    Job = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Job>.Entry(
                        "Job",
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Job_Stub,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Job_ComputeIsReadOnly,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Job_Validate,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Job_GetCoreImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Job_GetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Job_SetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Job_Refresh,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Job_OnValueChanged);
                private static void _Job_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Job>.Data> c, global::LightSwitchApplication.PlayVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._Job, sf);
                }
                private static bool _Job_ComputeIsReadOnly(global::LightSwitchApplication.PlayVolunteer e)
                {
                    bool result = false;
                    e.Job_IsReadOnly(ref result);
                    return result;
                }
                private static void _Job_Validate(global::LightSwitchApplication.PlayVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Job_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Job_GetCoreImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.Job;
                }
                private static global::LightSwitchApplication.Job _Job_GetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass>(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Job, ref d._Job);
                }
                private static void _Job_SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d, global::LightSwitchApplication.Job v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Job, ref d._Job, (i, ev) => i.Job = ev, v);
                }
                private static void _Job_Refresh(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Job, ref d._Job);
                }
                private static void _Job_OnValueChanged(global::LightSwitchApplication.PlayVolunteer e)
                {
                    e.Job_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Play>.Entry
                    Play = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Play>.Entry(
                        "Play",
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Play_Stub,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Play_ComputeIsReadOnly,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Play_Validate,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Play_GetCoreImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Play_GetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Play_SetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Play_Refresh,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Play_OnValueChanged);
                private static void _Play_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Play>.Data> c, global::LightSwitchApplication.PlayVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._Play, sf);
                }
                private static bool _Play_ComputeIsReadOnly(global::LightSwitchApplication.PlayVolunteer e)
                {
                    bool result = false;
                    e.Play_IsReadOnly(ref result);
                    return result;
                }
                private static void _Play_Validate(global::LightSwitchApplication.PlayVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Play_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Play_GetCoreImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.Play;
                }
                private static global::LightSwitchApplication.Play _Play_GetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Play, global::LightSwitchApplication.Play.DetailsClass>(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Play, ref d._Play);
                }
                private static void _Play_SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d, global::LightSwitchApplication.Play v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Play, ref d._Play, (i, ev) => i.Play = ev, v);
                }
                private static void _Play_Refresh(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Play, ref d._Play);
                }
                private static void _Play_OnValueChanged(global::LightSwitchApplication.PlayVolunteer e)
                {
                    e.Play_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>.Entry
                    Volunteer = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>.Entry(
                        "Volunteer",
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Volunteer_Stub,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Volunteer_ComputeIsReadOnly,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Volunteer_Validate,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Volunteer_GetCoreImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Volunteer_GetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Volunteer_SetImplementationValue,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Volunteer_Refresh,
                        global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties._Volunteer_OnValueChanged);
                private static void _Volunteer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>.Data> c, global::LightSwitchApplication.PlayVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._Volunteer, sf);
                }
                private static bool _Volunteer_ComputeIsReadOnly(global::LightSwitchApplication.PlayVolunteer e)
                {
                    bool result = false;
                    e.Volunteer_IsReadOnly(ref result);
                    return result;
                }
                private static void _Volunteer_Validate(global::LightSwitchApplication.PlayVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Volunteer_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Volunteer_GetCoreImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.Volunteer;
                }
                private static global::LightSwitchApplication.Volunteer _Volunteer_GetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass>(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Volunteer, ref d._Volunteer);
                }
                private static void _Volunteer_SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass d, global::LightSwitchApplication.Volunteer v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Volunteer, ref d._Volunteer, (i, ev) => i.Volunteer = ev, v);
                }
                private static void _Volunteer_Refresh(global::LightSwitchApplication.PlayVolunteer.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.PlayVolunteer.DetailsClass.PropertySetProperties.Volunteer, ref d._Volunteer);
                }
                private static void _Volunteer_OnValueChanged(global::LightSwitchApplication.PlayVolunteer e)
                {
                    e.Volunteer_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Data _PlayId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Data _VolunteerId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, int>.Data _JobId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, string>.Data _Notes;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Job>.Data _Job;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Play>.Data _Play;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>.Data _Volunteer;
            
        }
    
        #endregion
    }
    
    #endregion
}
