

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Job : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Job entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Job()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Job(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Job> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Job.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int JobId
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetValue(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.JobId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetValue(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Job.DetailsClass.SetValue(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.CourseVolunteer> CourseVolunteers
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetValue(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.CourseVolunteers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CourseVolunteer> CourseVolunteersQuery
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetQuery(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.CourseVolunteers);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.PlayVolunteer> PlayVolunteers
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetValue(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.PlayVolunteers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PlayVolunteer> PlayVolunteersQuery
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetQuery(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.PlayVolunteers);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ProductionVolunteer> ProductionVolunteers
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetValue(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.ProductionVolunteers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ProductionVolunteer> ProductionVolunteersQuery
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetQuery(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.ProductionVolunteers);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.VolunteerCapability> VolunteerCapabilities
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetValue(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.VolunteerCapabilities);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.VolunteerCapability> VolunteerCapabilitiesQuery
        {
            get
            {
                return global::LightSwitchApplication.Job.DetailsClass.GetQuery(this, global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.VolunteerCapabilities);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Job,
                global::LightSwitchApplication.Job.DetailsClass,
                global::LightSwitchApplication.Job.DetailsClass.IImplementation,
                global::LightSwitchApplication.Job.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.JobId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass>.Entry
                __JobEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass>.Entry(
                    global::LightSwitchApplication.Job.DetailsClass.__Job_CreateNew,
                    global::LightSwitchApplication.Job.DetailsClass.__Job_Created,
                    global::LightSwitchApplication.Job.DetailsClass.__Job_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Job __Job_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Job> es)
            {
                return new global::LightSwitchApplication.Job(es);
            }
            private static void __Job_Created(global::LightSwitchApplication.Job e)
            {
                e.Job_Created();
            }
            private static bool __Job_AllowSaveWithErrors(global::LightSwitchApplication.Job e)
            {
                bool result = false;
                e.Job_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Job.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, int> JobId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.JobId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.CourseVolunteer> CourseVolunteers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.CourseVolunteers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.CourseVolunteer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.PlayVolunteer> PlayVolunteers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.PlayVolunteers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.PlayVolunteer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.ProductionVolunteer> ProductionVolunteers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.ProductionVolunteers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.VolunteerCapability> VolunteerCapabilities
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.VolunteerCapabilities) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.VolunteerCapability>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int JobId { get; }
                new string Description { get; set; }
                new global::System.Collections.IEnumerable CourseVolunteers { get; }
                new global::System.Collections.IEnumerable PlayVolunteers { get; }
                new global::System.Collections.IEnumerable ProductionVolunteers { get; }
                new global::System.Collections.IEnumerable VolunteerCapabilities { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, int>.Entry
                    JobId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, int>.Entry(
                        "JobId",
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._JobId_Stub,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._JobId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._JobId_Validate,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._JobId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._JobId_OnValueChanged);
                private static void _JobId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Job.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, int>.Data> c, global::LightSwitchApplication.Job.DetailsClass d, object sf)
                {
                    c(d, ref d._JobId, sf);
                }
                private static bool _JobId_ComputeIsReadOnly(global::LightSwitchApplication.Job e)
                {
                    bool result = false;
                    e.JobId_IsReadOnly(ref result);
                    return result;
                }
                private static void _JobId_Validate(global::LightSwitchApplication.Job e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.JobId_Validate(r);
                }
                private static int _JobId_GetImplementationValue(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.ImplementationEntity.JobId;
                }
                private static void _JobId_OnValueChanged(global::LightSwitchApplication.Job e)
                {
                    e.JobId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Job.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, string>.Data> c, global::LightSwitchApplication.Job.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Job e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Job e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Job.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Job e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Entry
                    CourseVolunteers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Entry(
                        "CourseVolunteers",
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._CourseVolunteers_Stub,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._CourseVolunteers_GetReferencedEntities,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._CourseVolunteers_GetEntityCollection);
                private static void _CourseVolunteers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Job.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Data> c, global::LightSwitchApplication.Job.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseVolunteers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.CourseVolunteer> _CourseVolunteers_GetReferencedEntities(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.CourseVolunteer, global::LightSwitchApplication.CourseVolunteer.DetailsClass>(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.CourseVolunteers, ref d._CourseVolunteers);
                }
                private static global::System.Collections.IEnumerable _CourseVolunteers_GetEntityCollection(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseVolunteers;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.PlayVolunteer>.Entry
                    PlayVolunteers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.PlayVolunteer>.Entry(
                        "PlayVolunteers",
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._PlayVolunteers_Stub,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._PlayVolunteers_GetReferencedEntities,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._PlayVolunteers_GetEntityCollection);
                private static void _PlayVolunteers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Job.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.PlayVolunteer>.Data> c, global::LightSwitchApplication.Job.DetailsClass d, object sf)
                {
                    c(d, ref d._PlayVolunteers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.PlayVolunteer> _PlayVolunteers_GetReferencedEntities(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.PlayVolunteer, global::LightSwitchApplication.PlayVolunteer.DetailsClass>(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.PlayVolunteers, ref d._PlayVolunteers);
                }
                private static global::System.Collections.IEnumerable _PlayVolunteers_GetEntityCollection(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.ImplementationEntity.PlayVolunteers;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Entry
                    ProductionVolunteers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Entry(
                        "ProductionVolunteers",
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._ProductionVolunteers_Stub,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._ProductionVolunteers_GetReferencedEntities,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._ProductionVolunteers_GetEntityCollection);
                private static void _ProductionVolunteers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Job.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Data> c, global::LightSwitchApplication.Job.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductionVolunteers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ProductionVolunteer> _ProductionVolunteers_GetReferencedEntities(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass>(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.ProductionVolunteers, ref d._ProductionVolunteers);
                }
                private static global::System.Collections.IEnumerable _ProductionVolunteers_GetEntityCollection(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductionVolunteers;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.VolunteerCapability>.Entry
                    VolunteerCapabilities = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.VolunteerCapability>.Entry(
                        "VolunteerCapabilities",
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._VolunteerCapabilities_Stub,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._VolunteerCapabilities_GetReferencedEntities,
                        global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties._VolunteerCapabilities_GetEntityCollection);
                private static void _VolunteerCapabilities_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Job.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.VolunteerCapability>.Data> c, global::LightSwitchApplication.Job.DetailsClass d, object sf)
                {
                    c(d, ref d._VolunteerCapabilities, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.VolunteerCapability> _VolunteerCapabilities_GetReferencedEntities(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.VolunteerCapability, global::LightSwitchApplication.VolunteerCapability.DetailsClass>(global::LightSwitchApplication.Job.DetailsClass.PropertySetProperties.VolunteerCapabilities, ref d._VolunteerCapabilities);
                }
                private static global::System.Collections.IEnumerable _VolunteerCapabilities_GetEntityCollection(global::LightSwitchApplication.Job.DetailsClass d)
                {
                    return d.ImplementationEntity.VolunteerCapabilities;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, int>.Data _JobId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Data _CourseVolunteers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.PlayVolunteer>.Data _PlayVolunteers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Data _ProductionVolunteers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass, global::LightSwitchApplication.VolunteerCapability>.Data _VolunteerCapabilities;
            
        }
    
        #endregion
    }
    
    #endregion
}
