

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class ProductionVolunteer : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ProductionVolunteer entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProductionVolunteer()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProductionVolunteer(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProductionVolunteer> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ProductionVolunteer.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductionVolunteer_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductionVolunteer_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int VolunteerId
        {
            get
            {
                return global::LightSwitchApplication.ProductionVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.VolunteerId);
            }
            set
            {
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.VolunteerId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VolunteerId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VolunteerId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VolunteerId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int JobId
        {
            get
            {
                return global::LightSwitchApplication.ProductionVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.JobId);
            }
            set
            {
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.JobId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ProductionId
        {
            get
            {
                return global::LightSwitchApplication.ProductionVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.ProductionId);
            }
            set
            {
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.ProductionId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductionId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductionId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductionId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Notes
        {
            get
            {
                return global::LightSwitchApplication.ProductionVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Notes);
            }
            set
            {
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Notes, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Notes_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Notes_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Notes_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Job Job
        {
            get
            {
                return global::LightSwitchApplication.ProductionVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Job);
            }
            set
            {
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Job, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Production Production
        {
            get
            {
                return global::LightSwitchApplication.ProductionVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Production);
            }
            set
            {
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Production, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Production_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Production_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Production_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Volunteer Volunteer
        {
            get
            {
                return global::LightSwitchApplication.ProductionVolunteer.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Volunteer);
            }
            set
            {
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Volunteer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ProductionVolunteer,
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass,
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass.IImplementation,
                global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.VolunteerId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass>.Entry
                __ProductionVolunteerEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass>.Entry(
                    global::LightSwitchApplication.ProductionVolunteer.DetailsClass.__ProductionVolunteer_CreateNew,
                    global::LightSwitchApplication.ProductionVolunteer.DetailsClass.__ProductionVolunteer_Created,
                    global::LightSwitchApplication.ProductionVolunteer.DetailsClass.__ProductionVolunteer_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ProductionVolunteer __ProductionVolunteer_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProductionVolunteer> es)
            {
                return new global::LightSwitchApplication.ProductionVolunteer(es);
            }
            private static void __ProductionVolunteer_Created(global::LightSwitchApplication.ProductionVolunteer e)
            {
                e.ProductionVolunteer_Created();
            }
            private static bool __ProductionVolunteer_AllowSaveWithErrors(global::LightSwitchApplication.ProductionVolunteer e)
            {
                bool result = false;
                e.ProductionVolunteer_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int> VolunteerId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.VolunteerId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int> JobId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.JobId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int> ProductionId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.ProductionId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, string> Notes
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Notes) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Job> Job
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Job) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Job>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Production> Production
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Production) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Production>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer> Volunteer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Volunteer) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int VolunteerId { get; set; }
                new int JobId { get; set; }
                new int ProductionId { get; set; }
                new string Notes { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Job { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Production { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Volunteer { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Entry
                    VolunteerId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Entry(
                        "VolunteerId",
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._VolunteerId_Stub,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._VolunteerId_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._VolunteerId_Validate,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._VolunteerId_GetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._VolunteerId_SetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._VolunteerId_OnValueChanged);
                private static void _VolunteerId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._VolunteerId, sf);
                }
                private static bool _VolunteerId_ComputeIsReadOnly(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    bool result = false;
                    e.VolunteerId_IsReadOnly(ref result);
                    return result;
                }
                private static void _VolunteerId_Validate(global::LightSwitchApplication.ProductionVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VolunteerId_Validate(r);
                }
                private static int _VolunteerId_GetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.VolunteerId;
                }
                private static void _VolunteerId_SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, int v)
                {
                    d.ImplementationEntity.VolunteerId = v;
                }
                private static void _VolunteerId_OnValueChanged(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    e.VolunteerId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Entry
                    JobId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Entry(
                        "JobId",
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._JobId_Stub,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._JobId_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._JobId_Validate,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._JobId_GetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._JobId_SetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._JobId_OnValueChanged);
                private static void _JobId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._JobId, sf);
                }
                private static bool _JobId_ComputeIsReadOnly(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    bool result = false;
                    e.JobId_IsReadOnly(ref result);
                    return result;
                }
                private static void _JobId_Validate(global::LightSwitchApplication.ProductionVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.JobId_Validate(r);
                }
                private static int _JobId_GetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.JobId;
                }
                private static void _JobId_SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, int v)
                {
                    d.ImplementationEntity.JobId = v;
                }
                private static void _JobId_OnValueChanged(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    e.JobId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Entry
                    ProductionId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Entry(
                        "ProductionId",
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._ProductionId_Stub,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._ProductionId_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._ProductionId_Validate,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._ProductionId_GetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._ProductionId_SetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._ProductionId_OnValueChanged);
                private static void _ProductionId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductionId, sf);
                }
                private static bool _ProductionId_ComputeIsReadOnly(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    bool result = false;
                    e.ProductionId_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProductionId_Validate(global::LightSwitchApplication.ProductionVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProductionId_Validate(r);
                }
                private static int _ProductionId_GetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductionId;
                }
                private static void _ProductionId_SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ProductionId = v;
                }
                private static void _ProductionId_OnValueChanged(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    e.ProductionId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, string>.Entry
                    Notes = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, string>.Entry(
                        "Notes",
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Notes_Stub,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Notes_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Notes_Validate,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Notes_GetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Notes_SetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Notes_OnValueChanged);
                private static void _Notes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._Notes, sf);
                }
                private static bool _Notes_ComputeIsReadOnly(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    bool result = false;
                    e.Notes_IsReadOnly(ref result);
                    return result;
                }
                private static void _Notes_Validate(global::LightSwitchApplication.ProductionVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Notes_Validate(r);
                }
                private static string _Notes_GetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.Notes;
                }
                private static void _Notes_SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Notes = v;
                }
                private static void _Notes_OnValueChanged(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    e.Notes_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Job>.Entry
                    Job = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Job>.Entry(
                        "Job",
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Job_Stub,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Job_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Job_Validate,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Job_GetCoreImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Job_GetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Job_SetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Job_Refresh,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Job_OnValueChanged);
                private static void _Job_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Job>.Data> c, global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._Job, sf);
                }
                private static bool _Job_ComputeIsReadOnly(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    bool result = false;
                    e.Job_IsReadOnly(ref result);
                    return result;
                }
                private static void _Job_Validate(global::LightSwitchApplication.ProductionVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Job_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Job_GetCoreImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.Job;
                }
                private static global::LightSwitchApplication.Job _Job_GetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass>(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Job, ref d._Job);
                }
                private static void _Job_SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, global::LightSwitchApplication.Job v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Job, ref d._Job, (i, ev) => i.Job = ev, v);
                }
                private static void _Job_Refresh(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Job, ref d._Job);
                }
                private static void _Job_OnValueChanged(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    e.Job_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Production>.Entry
                    Production = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Production>.Entry(
                        "Production",
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Production_Stub,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Production_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Production_Validate,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Production_GetCoreImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Production_GetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Production_SetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Production_Refresh,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Production_OnValueChanged);
                private static void _Production_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Production>.Data> c, global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._Production, sf);
                }
                private static bool _Production_ComputeIsReadOnly(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    bool result = false;
                    e.Production_IsReadOnly(ref result);
                    return result;
                }
                private static void _Production_Validate(global::LightSwitchApplication.ProductionVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Production_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Production_GetCoreImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.Production;
                }
                private static global::LightSwitchApplication.Production _Production_GetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass>(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Production, ref d._Production);
                }
                private static void _Production_SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, global::LightSwitchApplication.Production v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Production, ref d._Production, (i, ev) => i.Production = ev, v);
                }
                private static void _Production_Refresh(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Production, ref d._Production);
                }
                private static void _Production_OnValueChanged(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    e.Production_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>.Entry
                    Volunteer = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>.Entry(
                        "Volunteer",
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Volunteer_Stub,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Volunteer_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Volunteer_Validate,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Volunteer_GetCoreImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Volunteer_GetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Volunteer_SetImplementationValue,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Volunteer_Refresh,
                        global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties._Volunteer_OnValueChanged);
                private static void _Volunteer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>.Data> c, global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, object sf)
                {
                    c(d, ref d._Volunteer, sf);
                }
                private static bool _Volunteer_ComputeIsReadOnly(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    bool result = false;
                    e.Volunteer_IsReadOnly(ref result);
                    return result;
                }
                private static void _Volunteer_Validate(global::LightSwitchApplication.ProductionVolunteer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Volunteer_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Volunteer_GetCoreImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.ImplementationEntity.Volunteer;
                }
                private static global::LightSwitchApplication.Volunteer _Volunteer_GetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass>(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Volunteer, ref d._Volunteer);
                }
                private static void _Volunteer_SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d, global::LightSwitchApplication.Volunteer v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Volunteer, ref d._Volunteer, (i, ev) => i.Volunteer = ev, v);
                }
                private static void _Volunteer_Refresh(global::LightSwitchApplication.ProductionVolunteer.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ProductionVolunteer.DetailsClass.PropertySetProperties.Volunteer, ref d._Volunteer);
                }
                private static void _Volunteer_OnValueChanged(global::LightSwitchApplication.ProductionVolunteer e)
                {
                    e.Volunteer_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Data _VolunteerId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Data _JobId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, int>.Data _ProductionId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, string>.Data _Notes;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Job>.Data _Job;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Production>.Data _Production;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass, global::LightSwitchApplication.Volunteer>.Data _Volunteer;
            
        }
    
        #endregion
    }
    
    #endregion
}
