

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Course : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Course entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Course()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Course(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Course> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Course.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int CourseId
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseId);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Year
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Year);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Year, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Year_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Year_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Year_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.CourseType CourseType
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseType);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Term Term
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Term);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Term, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Term_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Term_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Term_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.CourseAttendance> CourseAttendances
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseAttendances);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CourseAttendance> CourseAttendancesQuery
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetQuery(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseAttendances);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.CourseVolunteer> CourseVolunteers
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseVolunteers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CourseVolunteer> CourseVolunteersQuery
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetQuery(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseVolunteers);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Course,
                global::LightSwitchApplication.Course.DetailsClass,
                global::LightSwitchApplication.Course.DetailsClass.IImplementation,
                global::LightSwitchApplication.Course.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>.Entry
                __CourseEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>.Entry(
                    global::LightSwitchApplication.Course.DetailsClass.__Course_CreateNew,
                    global::LightSwitchApplication.Course.DetailsClass.__Course_Created,
                    global::LightSwitchApplication.Course.DetailsClass.__Course_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Course __Course_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Course> es)
            {
                return new global::LightSwitchApplication.Course(es);
            }
            private static void __Course_Created(global::LightSwitchApplication.Course e)
            {
                e.Course_Created();
            }
            private static bool __Course_AllowSaveWithErrors(global::LightSwitchApplication.Course e)
            {
                bool result = false;
                e.Course_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Course.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int> CourseId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>> Year
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Year) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseType> CourseType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Term> Term
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Term) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Term>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseAttendance> CourseAttendances
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseAttendances) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseAttendance>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseVolunteer> CourseVolunteers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseVolunteers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseVolunteer>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int CourseId { get; set; }
                new global::System.Nullable<int> Year { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation CourseType { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Term { get; set; }
                new global::System.Collections.IEnumerable CourseAttendances { get; }
                new global::System.Collections.IEnumerable CourseVolunteers { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Entry
                    CourseId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Entry(
                        "CourseId",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseId_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseId_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseId_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseId_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseId_OnValueChanged);
                private static void _CourseId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseId, sf);
                }
                private static bool _CourseId_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.CourseId_IsReadOnly(ref result);
                    return result;
                }
                private static void _CourseId_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CourseId_Validate(r);
                }
                private static int _CourseId_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseId;
                }
                private static void _CourseId_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, int v)
                {
                    d.ImplementationEntity.CourseId = v;
                }
                private static void _CourseId_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.CourseId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Entry
                    Year = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Year",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Year_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Year_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Year_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Year_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Year_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Year_OnValueChanged);
                private static void _Year_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._Year, sf);
                }
                private static bool _Year_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.Year_IsReadOnly(ref result);
                    return result;
                }
                private static void _Year_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Year_Validate(r);
                }
                private static global::System.Nullable<int> _Year_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.Year;
                }
                private static void _Year_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Year = v;
                }
                private static void _Year_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.Year_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseType>.Entry
                    CourseType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseType>.Entry(
                        "CourseType",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseType_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseType_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseType_GetCoreImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseType_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseType_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseType_Refresh,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseType_OnValueChanged);
                private static void _CourseType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseType>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseType, sf);
                }
                private static bool _CourseType_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.CourseType_IsReadOnly(ref result);
                    return result;
                }
                private static void _CourseType_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CourseType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _CourseType_GetCoreImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseType;
                }
                private static global::LightSwitchApplication.CourseType _CourseType_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.CourseType, global::LightSwitchApplication.CourseType.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseType, ref d._CourseType);
                }
                private static void _CourseType_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, global::LightSwitchApplication.CourseType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseType, ref d._CourseType, (i, ev) => i.CourseType = ev, v);
                }
                private static void _CourseType_Refresh(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseType, ref d._CourseType);
                }
                private static void _CourseType_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.CourseType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Term>.Entry
                    Term = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Term>.Entry(
                        "Term",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Term_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Term_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Term_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Term_GetCoreImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Term_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Term_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Term_Refresh,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Term_OnValueChanged);
                private static void _Term_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Term>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._Term, sf);
                }
                private static bool _Term_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.Term_IsReadOnly(ref result);
                    return result;
                }
                private static void _Term_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Term_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Term_GetCoreImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.Term;
                }
                private static global::LightSwitchApplication.Term _Term_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Term, ref d._Term);
                }
                private static void _Term_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, global::LightSwitchApplication.Term v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Term, ref d._Term, (i, ev) => i.Term = ev, v);
                }
                private static void _Term_Refresh(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Term, ref d._Term);
                }
                private static void _Term_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.Term_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseAttendance>.Entry
                    CourseAttendances = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseAttendance>.Entry(
                        "CourseAttendances",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseAttendances_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseAttendances_GetReferencedEntities,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseAttendances_GetEntityCollection);
                private static void _CourseAttendances_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseAttendance>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseAttendances, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.CourseAttendance> _CourseAttendances_GetReferencedEntities(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.CourseAttendance, global::LightSwitchApplication.CourseAttendance.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseAttendances, ref d._CourseAttendances);
                }
                private static global::System.Collections.IEnumerable _CourseAttendances_GetEntityCollection(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseAttendances;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Entry
                    CourseVolunteers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Entry(
                        "CourseVolunteers",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseVolunteers_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseVolunteers_GetReferencedEntities,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseVolunteers_GetEntityCollection);
                private static void _CourseVolunteers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseVolunteers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.CourseVolunteer> _CourseVolunteers_GetReferencedEntities(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.CourseVolunteer, global::LightSwitchApplication.CourseVolunteer.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseVolunteers, ref d._CourseVolunteers);
                }
                private static global::System.Collections.IEnumerable _CourseVolunteers_GetEntityCollection(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseVolunteers;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Data _CourseId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Data _Year;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseType>.Data _CourseType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Term>.Data _Term;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseAttendance>.Data _CourseAttendances;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseVolunteer>.Data _CourseVolunteers;
            
        }
    
        #endregion
    }
    
    #endregion
}
