

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Production : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Production entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Production()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Production(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Production> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Production.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Production_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Production_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ProductionId
        {
            get
            {
                return global::LightSwitchApplication.Production.DetailsClass.GetValue(this, global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.ProductionId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductionId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductionId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductionId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.Production.DetailsClass.GetValue(this, global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.Production.DetailsClass.SetValue(this, global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ProductionVolunteer> ProductionVolunteers
        {
            get
            {
                return global::LightSwitchApplication.Production.DetailsClass.GetValue(this, global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.ProductionVolunteers);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ProductionVolunteer> ProductionVolunteersQuery
        {
            get
            {
                return global::LightSwitchApplication.Production.DetailsClass.GetQuery(this, global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.ProductionVolunteers);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Production,
                global::LightSwitchApplication.Production.DetailsClass,
                global::LightSwitchApplication.Production.DetailsClass.IImplementation,
                global::LightSwitchApplication.Production.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.ProductionId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass>.Entry
                __ProductionEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass>.Entry(
                    global::LightSwitchApplication.Production.DetailsClass.__Production_CreateNew,
                    global::LightSwitchApplication.Production.DetailsClass.__Production_Created,
                    global::LightSwitchApplication.Production.DetailsClass.__Production_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Production __Production_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Production> es)
            {
                return new global::LightSwitchApplication.Production(es);
            }
            private static void __Production_Created(global::LightSwitchApplication.Production e)
            {
                e.Production_Created();
            }
            private static bool __Production_AllowSaveWithErrors(global::LightSwitchApplication.Production e)
            {
                bool result = false;
                e.Production_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Production.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, int> ProductionId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.ProductionId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, global::LightSwitchApplication.ProductionVolunteer> ProductionVolunteers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.ProductionVolunteers) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ProductionId { get; }
                new string Title { get; set; }
                new global::System.Collections.IEnumerable ProductionVolunteers { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, int>.Entry
                    ProductionId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, int>.Entry(
                        "ProductionId",
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._ProductionId_Stub,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._ProductionId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._ProductionId_Validate,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._ProductionId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._ProductionId_OnValueChanged);
                private static void _ProductionId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Production.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, int>.Data> c, global::LightSwitchApplication.Production.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductionId, sf);
                }
                private static bool _ProductionId_ComputeIsReadOnly(global::LightSwitchApplication.Production e)
                {
                    bool result = false;
                    e.ProductionId_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProductionId_Validate(global::LightSwitchApplication.Production e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProductionId_Validate(r);
                }
                private static int _ProductionId_GetImplementationValue(global::LightSwitchApplication.Production.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductionId;
                }
                private static void _ProductionId_OnValueChanged(global::LightSwitchApplication.Production e)
                {
                    e.ProductionId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Production.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, string>.Data> c, global::LightSwitchApplication.Production.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.Production e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.Production e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.Production.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.Production.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.Production e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Entry
                    ProductionVolunteers = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Entry(
                        "ProductionVolunteers",
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._ProductionVolunteers_Stub,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._ProductionVolunteers_GetReferencedEntities,
                        global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties._ProductionVolunteers_GetEntityCollection);
                private static void _ProductionVolunteers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Production.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Data> c, global::LightSwitchApplication.Production.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductionVolunteers, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ProductionVolunteer> _ProductionVolunteers_GetReferencedEntities(global::LightSwitchApplication.Production.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ProductionVolunteer, global::LightSwitchApplication.ProductionVolunteer.DetailsClass>(global::LightSwitchApplication.Production.DetailsClass.PropertySetProperties.ProductionVolunteers, ref d._ProductionVolunteers);
                }
                private static global::System.Collections.IEnumerable _ProductionVolunteers_GetEntityCollection(global::LightSwitchApplication.Production.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductionVolunteers;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, int>.Data _ProductionId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Production, global::LightSwitchApplication.Production.DetailsClass, global::LightSwitchApplication.ProductionVolunteer>.Data _ProductionVolunteers;
            
        }
    
        #endregion
    }
    
    #endregion
}
