

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Term : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Term entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Term()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Term(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Term> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Term.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Term_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Term_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int TermId
        {
            get
            {
                return global::LightSwitchApplication.Term.DetailsClass.GetValue(this, global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.TermId);
            }
            set
            {
                global::LightSwitchApplication.Term.DetailsClass.SetValue(this, global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.TermId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TermId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TermId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TermId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TermName
        {
            get
            {
                return global::LightSwitchApplication.Term.DetailsClass.GetValue(this, global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.TermName);
            }
            set
            {
                global::LightSwitchApplication.Term.DetailsClass.SetValue(this, global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.TermName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TermName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TermName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TermName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Course> Courses
        {
            get
            {
                return global::LightSwitchApplication.Term.DetailsClass.GetValue(this, global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.Courses);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Course> CoursesQuery
        {
            get
            {
                return global::LightSwitchApplication.Term.DetailsClass.GetQuery(this, global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.Courses);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Term,
                global::LightSwitchApplication.Term.DetailsClass,
                global::LightSwitchApplication.Term.DetailsClass.IImplementation,
                global::LightSwitchApplication.Term.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.TermId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass>.Entry
                __TermEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass>.Entry(
                    global::LightSwitchApplication.Term.DetailsClass.__Term_CreateNew,
                    global::LightSwitchApplication.Term.DetailsClass.__Term_Created,
                    global::LightSwitchApplication.Term.DetailsClass.__Term_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Term __Term_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Term> es)
            {
                return new global::LightSwitchApplication.Term(es);
            }
            private static void __Term_Created(global::LightSwitchApplication.Term e)
            {
                e.Term_Created();
            }
            private static bool __Term_AllowSaveWithErrors(global::LightSwitchApplication.Term e)
            {
                bool result = false;
                e.Term_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Term.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, int> TermId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.TermId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, string> TermName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.TermName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, global::LightSwitchApplication.Course> Courses
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.Courses) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, global::LightSwitchApplication.Course>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int TermId { get; set; }
                new string TermName { get; set; }
                new global::System.Collections.IEnumerable Courses { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, int>.Entry
                    TermId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, int>.Entry(
                        "TermId",
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermId_Stub,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermId_Validate,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermId_GetImplementationValue,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermId_SetImplementationValue,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermId_OnValueChanged);
                private static void _TermId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Term.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, int>.Data> c, global::LightSwitchApplication.Term.DetailsClass d, object sf)
                {
                    c(d, ref d._TermId, sf);
                }
                private static bool _TermId_ComputeIsReadOnly(global::LightSwitchApplication.Term e)
                {
                    bool result = false;
                    e.TermId_IsReadOnly(ref result);
                    return result;
                }
                private static void _TermId_Validate(global::LightSwitchApplication.Term e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TermId_Validate(r);
                }
                private static int _TermId_GetImplementationValue(global::LightSwitchApplication.Term.DetailsClass d)
                {
                    return d.ImplementationEntity.TermId;
                }
                private static void _TermId_SetImplementationValue(global::LightSwitchApplication.Term.DetailsClass d, int v)
                {
                    d.ImplementationEntity.TermId = v;
                }
                private static void _TermId_OnValueChanged(global::LightSwitchApplication.Term e)
                {
                    e.TermId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, string>.Entry
                    TermName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, string>.Entry(
                        "TermName",
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermName_Stub,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermName_Validate,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermName_GetImplementationValue,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermName_SetImplementationValue,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._TermName_OnValueChanged);
                private static void _TermName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Term.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, string>.Data> c, global::LightSwitchApplication.Term.DetailsClass d, object sf)
                {
                    c(d, ref d._TermName, sf);
                }
                private static bool _TermName_ComputeIsReadOnly(global::LightSwitchApplication.Term e)
                {
                    bool result = false;
                    e.TermName_IsReadOnly(ref result);
                    return result;
                }
                private static void _TermName_Validate(global::LightSwitchApplication.Term e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TermName_Validate(r);
                }
                private static string _TermName_GetImplementationValue(global::LightSwitchApplication.Term.DetailsClass d)
                {
                    return d.ImplementationEntity.TermName;
                }
                private static void _TermName_SetImplementationValue(global::LightSwitchApplication.Term.DetailsClass d, string v)
                {
                    d.ImplementationEntity.TermName = v;
                }
                private static void _TermName_OnValueChanged(global::LightSwitchApplication.Term e)
                {
                    e.TermName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, global::LightSwitchApplication.Course>.Entry
                    Courses = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, global::LightSwitchApplication.Course>.Entry(
                        "Courses",
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._Courses_Stub,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._Courses_GetReferencedEntities,
                        global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties._Courses_GetEntityCollection);
                private static void _Courses_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Term.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, global::LightSwitchApplication.Course>.Data> c, global::LightSwitchApplication.Term.DetailsClass d, object sf)
                {
                    c(d, ref d._Courses, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Course> _Courses_GetReferencedEntities(global::LightSwitchApplication.Term.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>(global::LightSwitchApplication.Term.DetailsClass.PropertySetProperties.Courses, ref d._Courses);
                }
                private static global::System.Collections.IEnumerable _Courses_GetEntityCollection(global::LightSwitchApplication.Term.DetailsClass d)
                {
                    return d.ImplementationEntity.Courses;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, int>.Data _TermId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, string>.Data _TermName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Term, global::LightSwitchApplication.Term.DetailsClass, global::LightSwitchApplication.Course>.Data _Courses;
            
        }
    
        #endregion
    }
    
    #endregion
}
