

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CrbCheck : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the CrbCheck entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CrbCheck()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CrbCheck(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CrbCheck> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CrbCheck.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CrbCheck_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CrbCheck_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int CrbCheckId
        {
            get
            {
                return global::LightSwitchApplication.CrbCheck.DetailsClass.GetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.CrbCheckId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CrbCheckId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CrbCheckId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CrbCheckId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CheckDate
        {
            get
            {
                return global::LightSwitchApplication.CrbCheck.DetailsClass.GetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.CheckDate);
            }
            set
            {
                global::LightSwitchApplication.CrbCheck.DetailsClass.SetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.CheckDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CrbNumber
        {
            get
            {
                return global::LightSwitchApplication.CrbCheck.DetailsClass.GetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.CrbNumber);
            }
            set
            {
                global::LightSwitchApplication.CrbCheck.DetailsClass.SetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.CrbNumber, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CrbNumber_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CrbNumber_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CrbNumber_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> OnlineFormSent
        {
            get
            {
                return global::LightSwitchApplication.CrbCheck.DetailsClass.GetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.OnlineFormSent);
            }
            set
            {
                global::LightSwitchApplication.CrbCheck.DetailsClass.SetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.OnlineFormSent, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OnlineFormSent_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OnlineFormSent_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OnlineFormSent_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> FormFilledOut
        {
            get
            {
                return global::LightSwitchApplication.CrbCheck.DetailsClass.GetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.FormFilledOut);
            }
            set
            {
                global::LightSwitchApplication.CrbCheck.DetailsClass.SetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.FormFilledOut, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FormFilledOut_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FormFilledOut_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FormFilledOut_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateCheckExpires
        {
            get
            {
                return global::LightSwitchApplication.CrbCheck.DetailsClass.GetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.DateCheckExpires);
            }
            set
            {
                global::LightSwitchApplication.CrbCheck.DetailsClass.SetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.DateCheckExpires, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCheckExpires_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCheckExpires_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCheckExpires_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> IdComplete
        {
            get
            {
                return global::LightSwitchApplication.CrbCheck.DetailsClass.GetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.IdComplete);
            }
            set
            {
                global::LightSwitchApplication.CrbCheck.DetailsClass.SetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.IdComplete, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IdComplete_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IdComplete_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IdComplete_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Volunteer Volunteer
        {
            get
            {
                return global::LightSwitchApplication.CrbCheck.DetailsClass.GetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.Volunteer);
            }
            set
            {
                global::LightSwitchApplication.CrbCheck.DetailsClass.SetValue(this, global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.Volunteer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Volunteer_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CrbCheck,
                global::LightSwitchApplication.CrbCheck.DetailsClass,
                global::LightSwitchApplication.CrbCheck.DetailsClass.IImplementation,
                global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.CrbCheckId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass>.Entry
                __CrbCheckEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass>.Entry(
                    global::LightSwitchApplication.CrbCheck.DetailsClass.__CrbCheck_CreateNew,
                    global::LightSwitchApplication.CrbCheck.DetailsClass.__CrbCheck_Created,
                    global::LightSwitchApplication.CrbCheck.DetailsClass.__CrbCheck_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CrbCheck __CrbCheck_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CrbCheck> es)
            {
                return new global::LightSwitchApplication.CrbCheck(es);
            }
            private static void __CrbCheck_Created(global::LightSwitchApplication.CrbCheck e)
            {
                e.CrbCheck_Created();
            }
            private static bool __CrbCheck_AllowSaveWithErrors(global::LightSwitchApplication.CrbCheck e)
            {
                bool result = false;
                e.CrbCheck_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, int> CrbCheckId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.CrbCheckId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>> CheckDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.CheckDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, string> CrbNumber
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.CrbNumber) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>> OnlineFormSent
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.OnlineFormSent) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>> FormFilledOut
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.FormFilledOut) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>> DateCheckExpires
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.DateCheckExpires) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>> IdComplete
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.IdComplete) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::LightSwitchApplication.Volunteer> Volunteer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.Volunteer) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::LightSwitchApplication.Volunteer>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int CrbCheckId { get; }
                new global::System.Nullable<global::System.DateTime> CheckDate { get; set; }
                new string CrbNumber { get; set; }
                new global::System.Nullable<global::System.DateTime> OnlineFormSent { get; set; }
                new global::System.Nullable<global::System.DateTime> FormFilledOut { get; set; }
                new global::System.Nullable<global::System.DateTime> DateCheckExpires { get; set; }
                new global::System.Nullable<global::System.DateTime> IdComplete { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Volunteer { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, int>.Entry
                    CrbCheckId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, int>.Entry(
                        "CrbCheckId",
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbCheckId_Stub,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbCheckId_ComputeIsReadOnly,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbCheckId_Validate,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbCheckId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbCheckId_OnValueChanged);
                private static void _CrbCheckId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CrbCheck.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, int>.Data> c, global::LightSwitchApplication.CrbCheck.DetailsClass d, object sf)
                {
                    c(d, ref d._CrbCheckId, sf);
                }
                private static bool _CrbCheckId_ComputeIsReadOnly(global::LightSwitchApplication.CrbCheck e)
                {
                    bool result = false;
                    e.CrbCheckId_IsReadOnly(ref result);
                    return result;
                }
                private static void _CrbCheckId_Validate(global::LightSwitchApplication.CrbCheck e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CrbCheckId_Validate(r);
                }
                private static int _CrbCheckId_GetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    return d.ImplementationEntity.CrbCheckId;
                }
                private static void _CrbCheckId_OnValueChanged(global::LightSwitchApplication.CrbCheck e)
                {
                    e.CrbCheckId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CheckDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CheckDate",
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CheckDate_Stub,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CheckDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CheckDate_Validate,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CheckDate_GetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CheckDate_SetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CheckDate_OnValueChanged);
                private static void _CheckDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CrbCheck.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.CrbCheck.DetailsClass d, object sf)
                {
                    c(d, ref d._CheckDate, sf);
                }
                private static bool _CheckDate_ComputeIsReadOnly(global::LightSwitchApplication.CrbCheck e)
                {
                    bool result = false;
                    e.CheckDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CheckDate_Validate(global::LightSwitchApplication.CrbCheck e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CheckDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CheckDate_GetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    return d.ImplementationEntity.CheckDate;
                }
                private static void _CheckDate_SetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CheckDate = global::LightSwitchApplication.CrbCheck.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CheckDate_OnValueChanged(global::LightSwitchApplication.CrbCheck e)
                {
                    e.CheckDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, string>.Entry
                    CrbNumber = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, string>.Entry(
                        "CrbNumber",
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbNumber_Stub,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbNumber_ComputeIsReadOnly,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbNumber_Validate,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbNumber_GetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbNumber_SetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._CrbNumber_OnValueChanged);
                private static void _CrbNumber_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CrbCheck.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, string>.Data> c, global::LightSwitchApplication.CrbCheck.DetailsClass d, object sf)
                {
                    c(d, ref d._CrbNumber, sf);
                }
                private static bool _CrbNumber_ComputeIsReadOnly(global::LightSwitchApplication.CrbCheck e)
                {
                    bool result = false;
                    e.CrbNumber_IsReadOnly(ref result);
                    return result;
                }
                private static void _CrbNumber_Validate(global::LightSwitchApplication.CrbCheck e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CrbNumber_Validate(r);
                }
                private static string _CrbNumber_GetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    return d.ImplementationEntity.CrbNumber;
                }
                private static void _CrbNumber_SetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CrbNumber = v;
                }
                private static void _CrbNumber_OnValueChanged(global::LightSwitchApplication.CrbCheck e)
                {
                    e.CrbNumber_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    OnlineFormSent = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "OnlineFormSent",
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._OnlineFormSent_Stub,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._OnlineFormSent_ComputeIsReadOnly,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._OnlineFormSent_Validate,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._OnlineFormSent_GetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._OnlineFormSent_SetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._OnlineFormSent_OnValueChanged);
                private static void _OnlineFormSent_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CrbCheck.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.CrbCheck.DetailsClass d, object sf)
                {
                    c(d, ref d._OnlineFormSent, sf);
                }
                private static bool _OnlineFormSent_ComputeIsReadOnly(global::LightSwitchApplication.CrbCheck e)
                {
                    bool result = false;
                    e.OnlineFormSent_IsReadOnly(ref result);
                    return result;
                }
                private static void _OnlineFormSent_Validate(global::LightSwitchApplication.CrbCheck e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.OnlineFormSent_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _OnlineFormSent_GetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    return d.ImplementationEntity.OnlineFormSent;
                }
                private static void _OnlineFormSent_SetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.OnlineFormSent = global::LightSwitchApplication.CrbCheck.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _OnlineFormSent_OnValueChanged(global::LightSwitchApplication.CrbCheck e)
                {
                    e.OnlineFormSent_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    FormFilledOut = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "FormFilledOut",
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._FormFilledOut_Stub,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._FormFilledOut_ComputeIsReadOnly,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._FormFilledOut_Validate,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._FormFilledOut_GetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._FormFilledOut_SetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._FormFilledOut_OnValueChanged);
                private static void _FormFilledOut_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CrbCheck.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.CrbCheck.DetailsClass d, object sf)
                {
                    c(d, ref d._FormFilledOut, sf);
                }
                private static bool _FormFilledOut_ComputeIsReadOnly(global::LightSwitchApplication.CrbCheck e)
                {
                    bool result = false;
                    e.FormFilledOut_IsReadOnly(ref result);
                    return result;
                }
                private static void _FormFilledOut_Validate(global::LightSwitchApplication.CrbCheck e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FormFilledOut_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _FormFilledOut_GetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    return d.ImplementationEntity.FormFilledOut;
                }
                private static void _FormFilledOut_SetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.FormFilledOut = global::LightSwitchApplication.CrbCheck.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _FormFilledOut_OnValueChanged(global::LightSwitchApplication.CrbCheck e)
                {
                    e.FormFilledOut_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateCheckExpires = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateCheckExpires",
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._DateCheckExpires_Stub,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._DateCheckExpires_ComputeIsReadOnly,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._DateCheckExpires_Validate,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._DateCheckExpires_GetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._DateCheckExpires_SetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._DateCheckExpires_OnValueChanged);
                private static void _DateCheckExpires_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CrbCheck.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.CrbCheck.DetailsClass d, object sf)
                {
                    c(d, ref d._DateCheckExpires, sf);
                }
                private static bool _DateCheckExpires_ComputeIsReadOnly(global::LightSwitchApplication.CrbCheck e)
                {
                    bool result = false;
                    e.DateCheckExpires_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateCheckExpires_Validate(global::LightSwitchApplication.CrbCheck e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateCheckExpires_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateCheckExpires_GetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    return d.ImplementationEntity.DateCheckExpires;
                }
                private static void _DateCheckExpires_SetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateCheckExpires = global::LightSwitchApplication.CrbCheck.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _DateCheckExpires_OnValueChanged(global::LightSwitchApplication.CrbCheck e)
                {
                    e.DateCheckExpires_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    IdComplete = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "IdComplete",
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._IdComplete_Stub,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._IdComplete_ComputeIsReadOnly,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._IdComplete_Validate,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._IdComplete_GetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._IdComplete_SetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._IdComplete_OnValueChanged);
                private static void _IdComplete_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CrbCheck.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.CrbCheck.DetailsClass d, object sf)
                {
                    c(d, ref d._IdComplete, sf);
                }
                private static bool _IdComplete_ComputeIsReadOnly(global::LightSwitchApplication.CrbCheck e)
                {
                    bool result = false;
                    e.IdComplete_IsReadOnly(ref result);
                    return result;
                }
                private static void _IdComplete_Validate(global::LightSwitchApplication.CrbCheck e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IdComplete_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _IdComplete_GetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    return d.ImplementationEntity.IdComplete;
                }
                private static void _IdComplete_SetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.IdComplete = global::LightSwitchApplication.CrbCheck.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _IdComplete_OnValueChanged(global::LightSwitchApplication.CrbCheck e)
                {
                    e.IdComplete_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::LightSwitchApplication.Volunteer>.Entry
                    Volunteer = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::LightSwitchApplication.Volunteer>.Entry(
                        "Volunteer",
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._Volunteer_Stub,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._Volunteer_ComputeIsReadOnly,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._Volunteer_Validate,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._Volunteer_GetCoreImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._Volunteer_GetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._Volunteer_SetImplementationValue,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._Volunteer_Refresh,
                        global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties._Volunteer_OnValueChanged);
                private static void _Volunteer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CrbCheck.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::LightSwitchApplication.Volunteer>.Data> c, global::LightSwitchApplication.CrbCheck.DetailsClass d, object sf)
                {
                    c(d, ref d._Volunteer, sf);
                }
                private static bool _Volunteer_ComputeIsReadOnly(global::LightSwitchApplication.CrbCheck e)
                {
                    bool result = false;
                    e.Volunteer_IsReadOnly(ref result);
                    return result;
                }
                private static void _Volunteer_Validate(global::LightSwitchApplication.CrbCheck e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Volunteer_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Volunteer_GetCoreImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    return d.ImplementationEntity.Volunteer;
                }
                private static global::LightSwitchApplication.Volunteer _Volunteer_GetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Volunteer, global::LightSwitchApplication.Volunteer.DetailsClass>(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.Volunteer, ref d._Volunteer);
                }
                private static void _Volunteer_SetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass d, global::LightSwitchApplication.Volunteer v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.Volunteer, ref d._Volunteer, (i, ev) => i.Volunteer = ev, v);
                }
                private static void _Volunteer_Refresh(global::LightSwitchApplication.CrbCheck.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CrbCheck.DetailsClass.PropertySetProperties.Volunteer, ref d._Volunteer);
                }
                private static void _Volunteer_OnValueChanged(global::LightSwitchApplication.CrbCheck e)
                {
                    e.Volunteer_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, int>.Data _CrbCheckId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CheckDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, string>.Data _CrbNumber;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _OnlineFormSent;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _FormFilledOut;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateCheckExpires;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _IdComplete;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CrbCheck, global::LightSwitchApplication.CrbCheck.DetailsClass, global::LightSwitchApplication.Volunteer>.Data _Volunteer;
            
        }
    
        #endregion
    }
    
    #endregion
}
